tools:
  debug_start:
    signature: debug_start <binary> [<args>]
    docstring: Starts a debug session with the given binary.
    arguments:
      - name: binary
        type: string
        description: the path to the binary to debug
        required: true
      - name: args
        type: string
        description: optional command-line arguments for the binary
        required: false
  debug_add_breakpoint:
    signature: debug_add_breakpoint <breakpoint>
    docstring: Adds a breakpoint in the debug session
    arguments:
      - name: breakpoint
        type: string
        description: The breakpoint location, which may be a function name, address, or filename and line number.
        required: true
  debug_continue:
    signature: debug_continue
    docstring: Continues the program execution in the debug session.
    arguments: []
  debug_step:
    signature: debug_step [number]
    docstring: Steps number of instructions in the debug session.
    arguments:
      - name: number
        type: integer
        description: number of instructions to step (default is 1)
        required: false
  debug_exec:
    signature: debug_exec <command>
    docstring: Executes arbitrary gdb command in debug session.
    arguments:
      - name: command
        type: string
        description: command to execute (wrap in single quotes to avoid shell escaping and substitution)
        required: true
  debug_stop:
    signature: debug_stop
    docstring: Stops the current debug session.
    arguments: []