name: Documentation improvement
description: Create a report to help us improve the documentation or add new documentation.
labels: ['documentation']

body:
- type: textarea
  attributes:
    label: Describe the issue
    description: >
      Tell us about the confusion introduced in the documentation *or*
      the information that is missing in the documentation.
  validations:
    required: true
- type: textarea
  attributes:
    label: Suggest a potential alternative/fix
    description: >
      Tell us how we could improve the documentation in this regard.