env:
  deployment:
    image: python:3.11
agent:
  tools:
    env_variables:
      WINDOW: 100
      OVERLAP: 2
    bundles:
      - tools/defaults
      - tools/search
      - tools/edit_linting
      - tools/submit
      - tools/state
    state_command: _state
    parse_function:
      type: thought_action
  history_processor:
    type: last_n_observations
    n: 5
  model:
    name: human
